import { defineCollection, z } from "astro:content";
import { glob } from "astro/loaders";

const site = defineCollection({
  loader: glob({ pattern: "site.md", base: "./src/content/site" }),
  schema: z.object({
    siteName: z.string().optional(),
    tagline: z.string().optional(),
    homepageEyebrow: z.string().optional(),
    homepageTitle: z.string().optional(),
    homepageIntro: z.string().optional(),
    careSheetsIntro: z.string().optional(),
    notesIntro: z.string().optional(),
    qrHelperHeading: z.string().optional(),
    qrHelperText: z.string().optional(),
    aboutHeading: z.string().optional(),
    aboutSummary: z.string().optional(),
    experienceText: z.string().optional(),
    focusText: z.string().optional(),
    credentialsText: z.string().optional(),
    groupsText: z.string().optional(),
    contactHeading: z.string().optional(),
    contactText: z.string().optional(),
    showContact: z.boolean().optional(),
    showCredentials: z.boolean().optional(),
    showGroups: z.boolean().optional(),
  }),
});

const completeFish = z.object({
  commonName: z.string(),
  scientificName: z.string(),
  origin: z.string(),
  temperatureRange: z.string(),
  adultSize: z.string(),
  tankSize: z.string(),
  foodRecommendation: z.string(),
  difficulty: z.string(),
  temperament: z.string(),
  plantSafe: z.boolean(),
  invertebrateSafe: z.boolean(),
  juvenileAppearance: z.string(),
  adultMaleAppearance: z.string(),
  adultFemaleAppearance: z.string(),
  maleFemaleDifferences: z.string(),
  husbandryNotes: z.string(),
  anthonyNotes: z.string(),
  relatedNoteSlugs: z.array(z.string()).optional(),
  qrSummary: z.string().optional(),
  quickWarnings: z.array(z.string()).optional(),
  mainImage: z.string(),
  juvenileImage: z.string(),
  maleImage: z.string(),
  femaleImage: z.string(),
  galleryImages: z.array(z.string()).optional(),
  summary: z.string(),
  draft: z.boolean().optional(),
});

const incompleteFish = z.object({
  commonName: z.string(),
  scientificName: z.string(),
  origin: z.string(),
  foodRecommendation: z.string(),
  temperament: z.string(),
  plantSafe: z.boolean(),
  invertebrateSafe: z.boolean(),
  adultMaleAppearance: z.string().optional(),
  temperatureRange: z.string().optional(),
  adultSize: z.string().optional(),
  tankSize: z.string().optional(),
  difficulty: z.string().optional(),
  juvenileAppearance: z.string().optional(),
  adultFemaleAppearance: z.string().optional(),
  maleFemaleDifferences: z.string().optional(),
  husbandryNotes: z.string().optional(),
  anthonyNotes: z.string().optional(),
  relatedNoteSlugs: z.array(z.string()).optional(),
  qrSummary: z.string().optional(),
  quickWarnings: z.array(z.string()).optional(),
  mainImage: z.string().optional(),
  juvenileImage: z.string().optional(),
  maleImage: z.string().optional(),
  femaleImage: z.string().optional(),
  galleryImages: z.array(z.string()).optional(),
  summary: z.string().optional(),
  draft: z.boolean().optional(),
});

const fish = defineCollection({
  loader: glob({ pattern: "**/*.md", base: "./src/content/fish" }),
  schema: z.union([completeFish, incompleteFish]),
});

const notes = defineCollection({
  loader: glob({ pattern: "**/*.md", base: "./src/content/notes" }),
  schema: z.object({
    title: z.string(),
    draft: z.boolean().optional(),
    category: z.string().optional(),
    tags: z.array(z.string()).optional(),
    relatedFishSlugs: z.array(z.string()).optional(),
    relatedNoteSlugs: z.array(z.string()).optional(),
    date: z.coerce.date(),
    lastUpdated: z.coerce.date(),
    summary: z.string(),
    quickAnswer: z.string().optional(),
    practicalSteps: z.array(z.string()).optional(),
    pictorialSteps: z.array(z.string()).optional(),
    sources: z.array(z.string()).optional(),
    lastReviewed: z.coerce.date().optional(),
    visualNote: z.string().optional(),
    illustrationsDataTechnique: z.string().optional(),
    galleryImages: z.array(z.string()).optional(),
  }),
});

export const collections = { site, fish, notes };
